name: Dataform CI

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  dataform-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dataform CLI
      run: npm i -g @dataform/cli@^2.3.2
      
    - name: Run Dataform tests
      run: dataform compile dataform_dw/
