name: Dataform Dry Run

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v2

          - name: create-json
            id: create-json
            uses: jsdaniell/create-json@1.1.2
            with:
              name: "df-credentials.json"
              json: ${{ secrets.GCP_CREDENTIALS }}
     
          - name : Authenticate Google Cloud
            id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: 'df-credentials.json'
              
          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: install
    
          - name: Execute Dataform dry run
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: run --dry-run
