name: Dataform Dry Run

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest
        permissions:
         contents: 'read'
         id-token: 'write'

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v4
     
          - name: Authenticate Google Cloud
            uses: google-github-actions/auth@v2
            with:
              service_account: 'dataform-dev@tushensu-data.iam.gserviceaccount.com'
              workload_identity_provider: 'projects/292560944911/locations/global/workloadIdentityPools/github/providers/my-repo'

          - name: Create credentials file 
            run: |
              mkdir github
              mkdir github/workspace
              touch github/workspace/.df-credentials.json
              cp '$GOOGLE_GHA_CREDS_PATH' github/workspace/.df-credentials.json
          
          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: install
    
          - name: Execute Dataform dry run
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: run --dry-run
