name: Dataform Dry Run

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v4
     
          - name : Authenticate Google Cloud
            uses: google-github-actions/auth@v2
            with:
              service_account: 'dataform-dev@tushensu-data.iam.gserviceaccount.com'
              workload_identity_provider: 'projects/292560944911/locations/global/workloadIdentityPools/github/providers/my-repo'
              
          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: install
    
          - name: Execute Dataform dry run
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: run --dry-run
