name: Dataform Dry Run

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code into workspace directory
            uses: actions/checkout@v2

          - name: Add execute permissions to decrytion file
            run: chmod +x ./decrypt_credentials.sh
            
          - name: Decrypt Dataform Credentials
            run: ./decrypt_credentials.sh 
            env:
              DATAFORM_PASSPHRASE: ${{ secrets.DATAFORM_PASSPHRASE }}
     
          - name : Authenticate Google Cloud
            id: 'auth'
            uses: 'google-github-actions/auth@v2'
            with:
              credentials_json: .df-credentials.json
              
          - name: Install Dataform dependencies
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: install
    
          - name: Execute Dataform dry run
            uses: docker://dataformco/dataform:2.8.3
            with:
                args: run --dry-run
