name: Dataform CI

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  dataform-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SQL Linting
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install Linter
      run: npm install -g sqlfluff
      
    - name: Run Linter
      run: sqlfluff lint --dialect bigquery dataform_dw/definitions/
